#NAME: Senyang Jiang, Max Zhang
#EMAIL: senyangjiang@yahoo.com, pipi-max@hotmail.com
#ID: 505111806, 205171726

all:
	@gcc -Wall -Wextra lab3a.c -o lab3a
dist:
	@tar -czf lab3a-505111806.tar.gz ext2_fs.h lab3a.c Makefile README
clean:
	@rm -f lab3a-505111806.tar.gz lab3a
